name: reminder
version: 0.1.0.0
github: "biesnecker/reminder"
license: BSD3
author: "John Biesnecker"
maintainer: "jbiesnecker@gmail.com"
copyright: "2020 John Biesnecker"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/biesnecker/reminder#readme>

dependencies:
  - attoparsec < 0.14
  - base >= 4.7 && < 5
  - optparse-applicative < 0.16
  - rainbow < 0.35
  - streaming < 0.3
  - text < 1.3
  - time < 2.0

executables:
  reminder:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
      - -Wcompat
